# Generated by Django 4.1.2 on 2022-11-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0002_alter_comment_author_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='softdesk_api.project'),
        ),
    ]
