# Generated by Django 4.1.2 on 2022-11-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0004_alter_issue_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='softdesk_api.issue'),
        ),
    ]
